services:
  app:
    container_name: google_shopping
    image: google-shopping:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:debug
    ports:
      - 30003:3000
    networks:
      - google_shopping_server
    volumes:
      - .:/usr/src/app
    # - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - db
      - phpmyadmin
  # Database
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '33063:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_MASTER_PASS}
      MYSQL_DATABASE: ${MYSQL_MASTER_DB}
      MYSQL_USER: ${MYSQL_MASTER_USER}
      MYSQL_PASSWORD: ${MYSQL_MASTER_PASS}
    networks:
      - google_shopping_server
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '803:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_MASTER_PASS}
    networks:
      - google_shopping_server
networks:
  google_shopping_server:
volumes:
  db_data:
